[package]
name = "boost_static_string"
description = "Boost C++ library boost_static_string packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_static_string"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_static_string"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]
boost_assert = { version = "0.1.0", path = "../boost_assert" }
boost_config = { version = "0.1.0", path = "../boost_config" }
boost_container_hash = { version = "0.1.0", path = "../boost_container_hash" }
boost_core = { version = "0.1.0", path = "../boost_core" }
boost_static_assert = { version = "0.1.0", path = "../boost_static_assert" }
boost_throw_exception = { version = "0.1.0", path = "../boost_throw_exception" }
boost_utility = { version = "0.1.0", path = "../boost_utility" }

[build-dependencies]
zanbil-boost-build = "0.1.0"
